#!/usr/bin/env bash
set -euo pipefail

mkdir -p "$HOME/Pictures/Screenshots"
mkdir -p "$HOME/Pictures/Wallpapers"
cp ./resources/wallpapers/* "$HOME/Pictures/Wallpapers/"

gsettings set org.gnome.desktop.interface color-scheme prefer-dark

git submodule init
git submodule update
pushd env/.config/nvim > /dev/null
git checkout main
popd > /dev/null