#!/usr/bin/env bash

if [ -z "$1" ]
  then
    echo "INFO: No image path specified. Reloading wallpaper..."
    feh --bg-scale $HOME/.feh_wallpaper.jpg
    exit
fi

file=$1
extension=$(echo $file | awk -F'[.]' '{print $NF}')

if [ $extension != "jpg" ] && [ $extension != "png" ]
  then
    echo "ERROR: Only jpg/png images are supported"
    exit
fi

file_directory=$(readlink -f $file)
destination_directory=$DEV_ENV/resources/.feh_wallpaper.jpg

cp $file_directory $destination_directory

feh --bg-scale $destination_directory
