#!/bin/sh
xrandr --output eDP-1 --mode 3840x2400 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-3-1 --off --output DP-3-2 --primary --mode 2560x1440 --pos 3840x0 --rotate normal --output DP-3-3 --mode 2560x1440 --pos 6405x0 --rotate normal
