#!/usr/bin/env bash

sudo pacman -Sy gimp
paru -S --noconfirm --needed fzf rofi-wayland btop curl wget bat ripgrep blueman pavucontrol peek openssh-server
sudo systemctl enable --now sshd
paru -S --needed postman-bin obsidian bruno-bin
paru -S ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
paru -S hyprlock --noconfirm --needed
paru -S ghostty --noconfirm --needed
paru -S hyprpaper hyprshot
