#!/usr/bin/env bash

paru -S --noconfirm --needed gimp fzf rofi-wayland btop curl wget bat ripgrep blueman pavucontrol peek openssh-server
sudo systemctl enable --now sshd
paru -S --needed postman-bin obsidian bruno-bin
paru -S ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
paru -S hyprlock --noconfirm --needed
paru -S ghostty --noconfirm --needed
