#!/usr/bin/env bash

sudo pacman -S --noconfirm neovim lua51 luarocks

git clone https://github.com/ThePrimeagen/harpoon.git $HOME/development/harpoon
cd $HOME/development/harpoon
git fetch
git checkout harpoon2

sudo luarocks install luacheck
