#!/usr/bin/env bash
set -euo pipefail

paru -S --needed --noconfirm npm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    . "$NVM_DIR/nvm.sh"
fi
nvm install --lts
nvm alias default 'lts/*'