#!/usr/bin/env bash

sudo apt install -y make gcc curl ffmpeg 7zip jq poppler-utils fd-find ripgrep fzf zoxide imagemagick

# rust btw
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update

git clone https://github.com/sxyazi/yazi.git $HOME/.yazi
cd $HOME/.yazi
cargo build --release --locked
mv target/release/yazi target/release/ya /usr/local/bin/
