#!/usr/bin/env bash
set -euo pipefail

paru -S --needed --noconfirm zsh
sudo chsh -s "$(command -v zsh)" "$USER"
RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"