#!/usr/bin/env bash
sudo apt -y update
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

if ! command -v git &> /dev/null; then
    sudo apt -y install git
fi

if [ ! -d $HOME/development/tomimelo ]; then
    mkdir -p $HOME/development/tomimelo
fi

git clone git@github.com:tomimelo/.dotfiles.git $HOME/development/tomimelo/.dotfiles

pushd $HOME/development/tomimelo/.dotfiles
./run
popd
