#!/bin/sh
display_1=${1:-DP-3-2}
display_2=${2:-DP-3-3}

xrandr --output eDP-1 --off --output DP-1 --off --output DP-3 --off --output DP-3 --off --output DP-3-1 --off --output $display_1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output $display_2 --mode 2560x1440 --pos 2560x0 --rotate normal
