#!/bin/sh
xrandr --output eDP-1 --primary --mode 3840x2400 --pos 0x1080 --rotate normal --scale 0.5x0.5 --output DP-1 --mode 1920x1080 --pos 894x0 --rotate normal --output DP-2 --off --output DP-3 --off
