preload = ~/Pictures/Wallpapers/wallpaper-1.jpg
preload = ~/Pictures/Wallpapers/wallpaper-2.png

wallpaper {
    monitor = DP-7
    path = ~/Pictures/Wallpapers/wallpaper-2.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-8
    path = ~/Pictures/Wallpapers/wallpaper-1.jpg
    fit_mode = cover
}

splash = false           # disable splash screen
ipc = on                 # enable runtime control (hyprctl hyprpaper)
